PUT  http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlJhZmlkQHBhdGhhby5jb20iLCJleHAiOjE3MzU4NTM2MDUsInVzZXJJZCI6OH0._HiS78JGYQDaNPMV1a-q7SMYNWyASyOtxst6OVltEIc

{
	"name" : "Rafid5",        
	"description" : "Welcome2" ,
	"location" : "AB",    
	"dateTime" : "2025-02-01T15:30:00.000Z"    
	
}